on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci
      - run: xvfb-run -a npm test
      - run: npx vsce pack
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: ${{ github.ref_type != 'tag' || !startsWith(github.ref_name, 'v') }}
          files: "*.vsix"
          fail_on_unmatched_files: false
